### PR TITLE
Build libncicore for Android 8

### PR DESCRIPTION
**Pull request by ilpianista**
ofono-ril-binder-plugin requires it

### CODE REVIEW

**Comment by mlehtima** [comment]
I think you mean that nfcd-binder-plugin requires it. Maybe you should move the change one line down so it's next to nfcd-binder-plugin so it's clearer why it's built.

**Comment by ilpianista** [comment]
> I think you mean that nfcd-binder-plugin requires it. Maybe you should move the change one line down so it's next to nfcd-binder-plugin so it's clearer why it's built.

Oh, you right. Fixed!

**Comment by mlehtima** [comment]
Sorry for not noticing the first time but your commit message doesn't follow the formatting used in the repo, could you change the commit message to "helpers: Build libncicore for Android 8"

**Comment by ilpianista** [comment]
> Sorry for not noticing the first time but your commit message doesn't follow the formatting used in the repo, could you change the commit message to "helpers: Build libncicore for Android 8"

No problem. Done

**Pull request merged**
