### PR TITLE
[ace][mce] Disable the PS due to MCE problem

### PR DESCRIPTION
**Pull request by piggz**

### CODE REVIEW

**Comment by sledges** [comment]
LGTM

**Comment by sledges** [comment]
Pls keep device names in lowercase. I'd suggest to use the following commit msg for proper tagging: "[ace][mce] Disable the PS due to MCE problem" <- and what problem?

**Comment by piggz** [comment]
MCE disables the TS until the PS is detected (or something like that).  Additionally, the PS doesnt work yet when mce and sensord are started in a particular order. Currently its easier to just disable the TS to get things working, until its fixed properly.

**Comment by sledges** [comment]
LGTM

**Pull request merged**
