### PR TITLE
[multirom] add the initramfs to the kernel rpm. contributes towards a…

### PR DESCRIPTION
**Pull request by alinelena**
… working zypper dup with multirom

### CODE REVIEW

**Comment by sledges** [comment]
@saukko, currently MultiROM devices don't have OTA because kernel cannot be flashed. MultiROM keeps kernel and initrd images on plain filesystem. We could split boot.img on device, but that's too costly, so we'd better ship initramfs together with kernel rpm, agree?

**Comment by saukko** [comment]
@sledges I think we should add macro has_multirom or something so that it would not change anything on existing systems.

**Comment by sledges** [comment]
then it's double work. MultiROM is distinguished by cmdline. Otherwise image build is exactly the same, and we don't want to end up building two images

**Comment by sledges** [comment]
delete_files is not in dhd, only in dh-configs for now; can we compromise on has_native_bootloader_only and put it on non-multirom devices, in this way the amount of modifications across all devices will be minimal (most ported devices don't mind having initrd shipped, and also they might get multirom eventually as well)

**Comment by sledges** [comment]
We forgot that ```have_custom_img_boot``` can be used for providing own whole package for e.g. .img type of adaptations as opposed to .zip, where partitioning/flashing is involved -- in that case it's certainly not a multirom device, so merging this PR is safe and not too cluttery.
Don't forget, we will also need adding -kernel package to patterns: https://github.com/mer-hybris/droid-config-hammerhead/blob/master/patterns/jolla-hw-adaptation-hammerhead.yaml#L13

**Pull request merged**
