### PR TITLE
helpers: Remove revision number check from ssu-kickstarts.

### PR DESCRIPTION
**Pull request by mkosola**

### CODE REVIEW

**Comment by Thaodan** [comment]
Aren't you removing the revision number rather than relaxing it?

**Comment by mkosola** [comment]
> Aren't you removing the revision number rather than relaxing it?

Adjusted commit message

**Comment by Thaodan** [comment]
Revision not version.

**Comment by mkosola** [comment]
> Revision not version.

done

**Review by Thaodan — APPROVED** [review]

**Pull request merged**
