### PR TITLE
N7100

### PR DESCRIPTION
**Pull request by JohnyZ89**
Added config files for galaxy samsung n7100

### CODE REVIEW

**Comment by sledges** [comment]
Thanks, sorry for not coming back earlier. Could you squash commits into one please?

**Comment by JohnyZ89** [comment]
Ok, commits squashed into one.

**Comment by sledges** [comment]
I'll be nit-picky :) please rename commit to something a bit clearer to readers (similar to what you had initially): "[n7100] Add configs for Samsung Galaxy Note II"
[tag] is needed for changelog and continuous integration bot automations, commit should be in present form, and viewers can immediately know what phone n7100 is :)

**Comment by JohnyZ89** [comment]
Sorry it took so long, but commit is renamed now.

**Comment by sledges** [comment]
Thanks, LGTM:)

**Pull request merged**
